### ISSUE TITLE
dont have HashCache.bin

### ISSUE THREAD

**Issue by tfqmstrmnd** [SuperTavor/Viola#1]
Hii

Thank you so much for ur hardwork, I already finished the merge process, but i have no idea for the pack process because of ((no HashCache.bin file found. Please download one or create one))do u know how to fix this?
![image](https://github.com/user-attachments/assets/55abc956-3e0f-452f-aacd-7188e7df0d1d)

**Comment by SuperTavor** [comment]
Hi. 
as i mentioned in the README, you can download hashcache files for your game and install them from the HashCache library folder in this repository. Please follow the "Getting started" guide here: https://github.com/SuperTavor/Viola?tab=readme-ov-file#alright-how-do-i-even-use-viola
