### ISSUE TITLE
Unhandled exception - The file is too long

### ISSUE THREAD

**Issue by HazzyDevil** [SuperTavor/Viola#2]
Hello, 

I tested your program on one piece burning blood on pc which also has cpk files. It worked on the smaller cpks, but gave an error on the bigger one with the following warning/error:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.IO.IOException: The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size.
>    at System.IO.File.ReadAllBytes(String path)
>    at Viola.Core.Dump.Logic.CDump.DumpRomfs()
>    at Viola.Core.Launcher.Logic.CLauncher.BeginDump()
>    at Viola.Core.Launcher.Logic.CLauncher.<LaunchAsync>b__5_0()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at Viola.Core.Launcher.Logic.CLauncher.LaunchAsync()
>    at Viola.WinForms.Forms.MainForm.MainForm.CommonMode(Mode mode, Boolean saveFile, String inputFileMessage, String outputFileMessage, String specificCpkListPath, String saveFileFilter, Platform targetPlat, Boolean isUseTargetPlat)
>    at Viola.WinForms.Forms.MainForm.MainForm.dumpBtn_Click(Object sender, EventArgs e)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
>    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

Any chance in adapting your program for larger cpks?

**Comment by SuperTavor** [comment]
Hey there
I didn't write the CPK logic, so I would not know how to change this. Furthermore, Viola is intended as a mod loader for LEVEL5 games, afaik this game does not use a cpklist, which would render Viola redundant. Just use a normal cpk extractor.
